# Generated by Django 5.0.1 on 2024-01-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.FilePathField(max_length=256)),
                ("content", models.FileField(upload_to="files")),
            ],
        ),
    ]
