# Generated by Django 5.0.1 on 2024-01-26 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filemanger", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="name",
        ),
    ]
