# Generated by Django 5.0.1 on 2024-02-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanger", "0002_remove_document_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "fileupload"),
                    (2, "filepreprocess"),
                    (3, "ImageTextGenerate"),
                    (4, "ImagerDescriptionReview"),
                    (5, "indexed"),
                ],
                default=1,
            ),
        ),
    ]
