# Generated by Django 5.0.1 on 2024-02-06 08:47

import filemanger.custome_storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanger", "0003_document_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.FileField(
                storage=filemanger.custome_storage.OverwriteStorage(), upload_to="files"
            ),
        ),
    ]
