# Generated by Django 5.0.1 on 2024-02-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanger", "0004_alter_document_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
