# Generated by Django 5.0.1 on 2024-02-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanger", "0005_document_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_name",
            field=models.CharField(default="defult", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
