# Generated by Django 5.0.1 on 2024-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanger", "0006_document_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "fileupload"),
                    (2, "filepreprocess"),
                    (3, "featureextraction"),
                    (4, "ImageTextGenerate"),
                    (5, "ImagerDescriptionReview"),
                    (6, "indexed"),
                ],
                default=1,
            ),
        ),
    ]
