# Generated by Django 5.0.1 on 2024-02-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanger", "0007_alter_document_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=255)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Package"), (2, "class"), (3, "Method")], default=3
                    ),
                ),
                ("chromaDb_id", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
