# Generated by Django 5.0.1 on 2024-02-20 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filemanger", "0008_record"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Record",
        ),
    ]
